### PR TITLE
removed package version of appconfig scripts inside image

### PR DESCRIPTION
**Pull request by Supekar**

### CODE REVIEW

**Comment by joel-bluedata** [comment]
This works with the current image tag in the kdapp?

BTW I would strongly recommend using something other than "latest" for your image, since this will prevent existing kdapp installations from breaking when the image later changes. Let me know if there's some issue with this.

**Comment by kmathur2** [comment]
> This works with the current image tag in the kdapp?
> 
> BTW I would strongly recommend using something other than "latest" for your image, since this will prevent existing kdapp installations from breaking when the image later changes. Let me know if there's some issue with this.

@joel-bluedata  The reasoning for the 'latest' tag is to avoid making changes to KD as we find and fix issues in app config/docker scripts. Bad idea?

**Comment by swamibluedata** [comment]
Also pl. remove docker.io prefix from all the json

**Comment by joel-bluedata** [comment]
@kmathur2 OK I see. We do need to be double sure not to leave it in that state for any official release though. If you guys want to handle things that way I'm willing to try it but file a GitHub issue against the 0.5 milestone here, with a list of the specific kdapps that need to get final image tags.

**Comment by Supekar** [comment]
maybe if the tag 'latest' isn't suitable, we can set it to something else for all images for the latest release

**Comment by joel-bluedata** [comment]
Well, the general point is that when we release something the tag it refers to should always point to the same image and never change.

Anyway as I said above I'm fine with "latest" for now (during ongoing development), but if you do want to do that then file an issue to fix it before release.

Swami also had a concern above.

**Comment by joel-bluedata** [comment]
Just FYI before we merge this I'm waiting on one of two things: either using a specific tag (not latest), or else an issue filed to do so before 0.5 release.

**Comment by Supekar** [comment]
Created a Jira ticket for KD app labels to be updated.
https://jira-pro.its.hpecorp.net:8443/browse/BDP-1585

**Pull request merged**
