### PR TITLE
#507 Use NVIDIA_VISIBLE_DEVICES=VOID workaround for all nvidia resources

### PR DESCRIPTION
**Pull request by aleshchynskyi**

### CODE REVIEW

**Comment by aleshchynskyi** [comment]
> Looks plausible to me. Have you been able to functionally verify that GPU-using apps and MIG cases still work?

I don't have an environment with MIGs, so currently just an ordinary test cases

**Comment by joel-bluedata** [comment]
OK let's come back to this one. From the discussion/updates on issue #507 I think this is pretty much what we want, except maybe setting a value of "void" as opposed to "VOID".

Need to get an environment to test.

**Comment by joel-bluedata** [comment]
closes #507

**Review by joel-bluedata — APPROVED** [review]
Merging this to enable easier/wider testing.

**Pull request merged**
