### PR TITLE
Reverting the namingScheme changes.

### PR DESCRIPTION
**Pull request by koshiksamota10**

### CODE REVIEW

**Comment by kmathur2** [comment]
why are we taking this out?

**Comment by koshiksamota10** [comment]
Joel found an issue in his testing referred here: https://github.com/bluek8s/kubedirector/issues/309#issuecomment-658484754

**Comment by joel-bluedata** [comment]
Yah unfortunately. Thanks Koshik; I do like the gist of this and look forward to getting it whipped into shape for the next release.

**Comment by joel-bluedata** [comment]
I'll handle updating the KD addon in everest accordingly.

**Comment by koshiksamota10** [comment]
Thanks Joel!

**Pull request merged**
